---
# tasks file for inah-module

- name: Create pip config folder
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_env.HOME }}/.config/pip"
    mode: 0700

- name: Add pip credentials to nexus
  ansible.builtin.template:
    src: pip.conf.j2
    dest: "{{ ansible_env.HOME }}/.config/pip/pip.conf"
    mode: 0600

- name: "Import task for install with nexus"
  ansible.builtin.include_tasks:
    file: nexus.yml
  when: use_nexus|bool

- name: "Import task for install with file"
  ansible.builtin.include_tasks:
    file: local.yml
  when: not use_nexus|bool
